# Generated by Django 5.2.3 on 2025-06-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prova', models.IntegerField(unique=True)),
                ('gabarito', models.CharField(max_length=100)),
                ('pesos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura', models.CharField(max_length=100)),
                ('nota', models.FloatField()),
                ('erro', models.IntegerField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participante')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prova')),
            ],
        ),
    ]
